- name: GitHub Pages
  on:
    push:
      tags:
        - "*"
  # uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
  uses: crazy-max/ghaction-github-pages@v2.6.0
  with:
    # Build directory to deploy
    build_dir: dist
